# Generated by Django 6.0.2 on 2026-03-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AddField(
            model_name='place',
            name='image1',
            field=models.ImageField(blank=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='place',
            name='image2',
            field=models.ImageField(blank=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='place',
            name='image3',
            field=models.ImageField(blank=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='place',
            name='image4',
            field=models.ImageField(blank=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='subtitle_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
