# Generated by Django 6.0.2 on 2026-03-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_place_image_place_image1_place_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='price_ar',
        ),
        migrations.RemoveField(
            model_name='place',
            name='price_en',
        ),
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.CharField(default='KD 0.000', max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
    ]
